// <auto-generated />
using System;
using CodeFirst_Entity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst_Entity.Migrations
{
    [DbContext(typeof(CodeFirstContext))]
    [Migration("20200410205830_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CodeFirst_Entity.Models.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CustPhone")
                        .HasColumnType("bigint");

                    b.Property<int?>("NoOfOrders")
                        .HasColumnType("int");

                    b.HasKey("CustId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CodeFirst_Entity.Models.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FkCustId")
                        .HasColumnType("int");

                    b.Property<int?>("FkProdId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("FkCustId");

                    b.HasIndex("FkProdId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CodeFirst_Entity.Models.Products", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProdName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProdPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProdId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CodeFirst_Entity.Models.Orders", b =>
                {
                    b.HasOne("CodeFirst_Entity.Models.Customer", "FkCust")
                        .WithMany("Orders")
                        .HasForeignKey("FkCustId");

                    b.HasOne("CodeFirst_Entity.Models.Products", "FkProd")
                        .WithMany("Orders")
                        .HasForeignKey("FkProdId");
                });
#pragma warning restore 612, 618
        }
    }
}
