USE [master]
GO
/****** Object:  Database [DB_FIRST]    Script Date: 10-04-2020 23:52:48 ******/
CREATE DATABASE [DB_FIRST]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_FIRST', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DB_FIRST.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_FIRST_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DB_FIRST_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DB_FIRST] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_FIRST].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_FIRST] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_FIRST] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_FIRST] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_FIRST] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_FIRST] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_FIRST] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [DB_FIRST] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_FIRST] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_FIRST] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_FIRST] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_FIRST] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_FIRST] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_FIRST] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_FIRST] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_FIRST] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DB_FIRST] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_FIRST] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_FIRST] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_FIRST] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_FIRST] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_FIRST] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_FIRST] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_FIRST] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DB_FIRST] SET  MULTI_USER 
GO
ALTER DATABASE [DB_FIRST] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_FIRST] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_FIRST] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_FIRST] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_FIRST] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_FIRST] SET QUERY_STORE = OFF
GO
USE [DB_FIRST]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 10-04-2020 23:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CustomerID] [int] NOT NULL,
	[CustomerName] [varchar](30) NULL,
	[CustomerAdd] [varchar](40) NULL,
	[NoOfOrder] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 10-04-2020 23:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[OrderID] [int] NOT NULL,
	[FKCustID] [int] NULL,
	[FKProdID] [int] NULL,
	[OrderAmount] [int] NULL,
	[OrderDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[OrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 10-04-2020 23:52:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[ProdID] [int] NOT NULL,
	[PrOdName] [varchar](30) NULL,
	[ProdPrice] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProdID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [DB_FIRST] SET  READ_WRITE 
GO
